
public class BingLanguages {
	public static final String[][] SUPPORTED_LANGUAGES = new String[][] {
		{"af", "Afrikaans"},
		{"az", "Azərbaycan (Azerbaijani)"},
		{"ba", "Bashkir"},
		{"bs", "Bosnian"},
		{"ca", "Català (Catalan)"},
		{"cy", "Cymraeg (Welsh)"},
		{"da", "Dansk (Danish)"},
		{"de", "Deutsch (German)"},
		{"et", "Eesti (Estonian)"},
		{"en", "English"},
		{"es", "Español (Spanish)"},
		{"fil", "Filipino"},
		{"fr-CA", "Français (Canada)"},
		{"fr", "Français (French)"},
		{"ga", "Gaeilge (Irish)"},
		{"sm", "Gagana Sāmoa (Samoan)"},
		{"ht", "Haitian Creole"},
		{"mww", "Hmong Daw"},
		{"hr", "Hrvatski (Croatian)"},
		{"otq", "Hñähñu (Querétaro Otomi)"},
		{"id", "Indonesia (Indonesian)"},
		{"it", "Italiano (Italian)"},
		{"sw", "Kiswahili (Swahili)"},
		{"tlh-Latn", "Klingon (Latin)"},
		{"tlh-Piqd", "Klingon (pIqaD)"},
		{"kmr", "Kurdî (Bakur) / Kurdish (Northern)"},
		{"ku", "Kurdî (Navîn) / Kurdish (Central)"},
		{"ky", "Kyrgyz"},
		{"lv", "Latviešu (Latvian)"},
		{"to", "Lea Fakatonga (Tongan)"},
		{"lt", "Lietuvių (Lithuanian)"},
		{"hu", "Magyar (Hungarian)"},
		{"mg", "Malagasy"},
		{"mt", "Malti (Maltese)"},
		{"ms", "Melayu (Malay)"},
		{"mn-Cyrl", "Mongolian (Cyrillic)"},
		{"fj", "Na Vosa Vakaviti (Fijian)"},
		{"nl", "Nederlands (Dutch)"},
		{"nb", "Norsk Bokmål (Norwegian)"},
		{"pl", "Polski (Polish)"},
		{"pt", "Português (Brasil)"},
		{"pt-PT", "Português (Portugal)"},
		{"ty", "Reo Tahiti (Tahitian)"},
		{"ro", "Română (Romanian)"},
		{"sq", "Shqip (Albanian)"},
		{"sk", "Slovenčina (Slovak)"},
		{"sl", "Slovenščina (Slovenian)"},
		{"sr-Latn", "Srpski (latinica) / Serbian (Latin)"},
		{"fi", "Suomi (Finnish)"},
		{"sv", "Svenska (Swedish)"},
		{"mi", "Te Reo Māori (Māori)"},
		{"vi", "Tiếng Việt (Vietnamese)"},
		{"tk", "Türkmen Dili (Turkmen)"},
		{"tr", "Türkçe (Turkish)"},
		{"uz", "Uzbek (Latin)"},
		{"yua", "Yucatec Maya"},
		{"is", "Íslenska (Icelandic)"},
		{"cs", "Čeština (Czech)"},
		{"el", "Ελληνικά (Greek)"},
		{"bg", "Български (Bulgarian)"},
		{"mk", "Македонски (Macedonian)"},
		{"ru", "Русский (Russian)"},
		{"sr-Cyrl", "Српски (ћирилица) / Serbian (Cyrillic)"},
		{"tt", "Татар (Tatar)"},
		{"uk", "Українська (Ukrainian)"},
		{"kk", "Қазақ Тілі (Kazakh)"},
		{"hy", "Հայերեն (Armenian)"},
		{"he", "עברית (Hebrew)"},
		{"ug", "ئۇيغۇرچە (Uyghur)"},
		{"ur", "اردو (Urdu)"},
		{"ar", "العربية (Arabic)"},
		{"prs", "دری (Dari)"},
		{"fa", "فارسی (Persian)"},
		{"ps", "پښتو (Pashto)"},
		{"dv", "ދިވެހިބަސް (Divehi)"},
		{"ne", "नेपाली (Nepali)"},
		{"mr", "मराठी (Marathi)"},
		{"hi", "हिन्दी (Hindi)"},
		{"as", "অসমীয়া (Assamese)"},
		{"bn", "বাংলা (Bangla)"},
		{"pa", "ਪੰਜਾਬੀ (Punjabi)"},
		{"gu", "ગુજરાતી (Gujarati)"},
		{"or", "ଓଡ଼ିଆ (Odia)"},
		{"ta", "தமிழ் (Tamil)"},
		{"te", "తెలుగు (Telugu)"},
		{"kn", "ಕನ್ನಡ (Kannada)"},
		{"ml", "മലയാളം (Malayalam)"},
		{"th", "ไทย (Thai)"},
		{"lo", "ລາວ (Lao)"},
		{"bo", "བོད་སྐད་ (Tibetan)"},
		{"my", "မြန်မာ / Myanmar (Burmese)"},
		{"ka", "ქართული (Georgian)"},
		{"ti", "ትግር (Tigrinya)"},
		{"am", "አማርኛ (Amharic)"},
		{"iu", "ᐃᓄᒃᑎᑐᑦ (Inuktitut)"},
		{"km", "ខ្មែរ (Khmer)"},
		{"mn-Mong", "ᠮᠣᠩᠭᠣᠯ ᠬᠡᠯᠡ / Mongolian (Traditional)"},
		{"lzh", "中文 (文言文) / Chinese (Literary)"},
		{"zh-Hans", "中文 (简体) / Chinese Simplified"},
		{"ja", "日本語 (Japanese)"},
		{"yue", "粵語 (繁體) / Cantonese (Traditional)"},
		{"zh-Hant", "繁體中文 (繁體) / Chinese Traditional"},
		{"ko", "한국어 (Korean)"}
	};
}
